"""
SQL Audit Scanner - Report generator

Produces professional JSON reports suitable for delivery to a client.
No raw user data is included; only technical proof-of-concept details.
"""
import json
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

import sys
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from config import LOGS_DIR, REPORTS_DIR
from backend.utils.logger import setup_logger

logger = setup_logger("reporter", LOGS_DIR / "scanner.log")

_TOOL_VERSION = "1.0.0"

_SEVERITY_ORDER = ["critical", "high", "medium", "low", "info"]


class ReportGenerator:
    """Build and persist JSON audit reports."""

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def generate(
        self,
        *,
        scan_id: str,
        url: str,
        findings: List[Dict[str, Any]],
        status: str,
        start_time: datetime,
        end_time: datetime,
        error: Optional[str] = None,
    ) -> Dict[str, Any]:
        """Create, save, and return a report dict."""
        duration = round((end_time - start_time).total_seconds(), 2)

        # Sort findings: critical first, info last
        sorted_findings = sorted(
            findings,
            key=lambda f: _SEVERITY_ORDER.index(f.get("severity", "info"))
            if f.get("severity", "info") in _SEVERITY_ORDER
            else 99,
        )

        severity_count = {s: 0 for s in _SEVERITY_ORDER}
        for f in sorted_findings:
            sev = f.get("severity", "info")
            if sev in severity_count:
                severity_count[sev] += 1

        risk_level = self._overall_risk(severity_count)
        vulnerable = severity_count["critical"] > 0 or severity_count["high"] > 0

        report: Dict[str, Any] = {
            "report_metadata": {
                "tool": "SQL Audit Scanner",
                "version": _TOOL_VERSION,
                "generated_at": datetime.utcnow().isoformat() + "Z",
                "disclaimer": (
                    "This report was generated by an authorised security audit tool. "
                    "Its contents are confidential and intended solely for authorised "
                    "personnel. Do not distribute without explicit permission."
                ),
            },
            "scan_id": scan_id,
            "target": url,
            "date": start_time.isoformat(),
            "end_date": end_time.isoformat(),
            "duration_seconds": duration,
            "status": status,
            "summary": {
                "total_findings": len(sorted_findings),
                "risk_level": risk_level,
                "severity_breakdown": severity_count,
                "vulnerable": vulnerable,
            },
            "findings": sorted_findings,
            "error": error,
        }

        self._save(scan_id, report)
        return report

    def load(self, scan_id: str) -> Optional[Dict[str, Any]]:
        """Load a previously saved report, or None if not found."""
        path = REPORTS_DIR / f"{scan_id}.json"
        if not path.exists():
            return None
        try:
            return json.loads(path.read_text(encoding="utf-8"))
        except Exception as exc:
            logger.error(f"Cannot load report {scan_id}: {exc}")
            return None

    def list_all(self) -> List[Dict[str, Any]]:
        """Return a summary list of all saved reports, newest first."""
        summaries = []
        for f in sorted(REPORTS_DIR.glob("*.json"), key=lambda p: p.stat().st_mtime, reverse=True):
            try:
                data = json.loads(f.read_text(encoding="utf-8"))
                summaries.append(
                    {
                        "scan_id": data.get("scan_id"),
                        "target": data.get("target"),
                        "date": data.get("date"),
                        "status": data.get("status"),
                        "risk_level": data.get("summary", {}).get("risk_level", "N/A"),
                        "total_findings": data.get("summary", {}).get("total_findings", 0),
                        "vulnerable": data.get("summary", {}).get("vulnerable", False),
                    }
                )
            except Exception as exc:
                logger.warning(f"Skipping malformed report {f.name}: {exc}")
        return summaries

    def delete(self, scan_id: str) -> bool:
        """Delete a report file. Returns True if deleted."""
        path = REPORTS_DIR / f"{scan_id}.json"
        if path.exists():
            path.unlink()
            logger.info(f"Report {scan_id} deleted")
            return True
        return False

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _save(self, scan_id: str, report: Dict[str, Any]) -> None:
        path = REPORTS_DIR / f"{scan_id}.json"
        path.write_text(json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8")
        logger.info(f"Report saved → {path}")

    @staticmethod
    def _overall_risk(counts: Dict[str, int]) -> str:
        for level in _SEVERITY_ORDER:
            if counts.get(level, 0) > 0:
                return level.upper()
        return "NONE"
